### ISSUE TITLE
Error Loading Webpage

### ISSUE THREAD

**Issue by RihanArfan** [IntellectualSites/plotwebphp#2]
I have downloaded this, put it in my WebServer which has PHP. I've set up the configuration correctly, but viewing the site causes this error to be brought up.

`Fatal error: Cannot declare class ParseError, because the name is already in use in C:\XAMPP\htdocs\Application\PlotWeb\lib\h2o\h2o\errors.php on line 6`

**Comment by buchin** [comment]
That's because since PHP7, PHP has it's own ParseError class. 
http://php.net/manual/en/class.parseerror.php
